##### 服务端相关配置 #####
server:
  # 配置api端口号
  port: 8080
  servlet:
    # 配置context-path, 一般来说这个配置在正式发布的时候不配置
    context-path: /
    # session最大超时时间(分钟)，默认为30分钟
    session:
      timeout: 60
  error:
    # 错误页，指定发生错误时，跳转的URL --> BasicErrorController
    path: /error
  # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败,
  # 只有特殊需求的情况下才配置, 具体根据各自的业务来设置
  address: 127.0.0.1
  tomcat:
    # tomcat最大线程数, 默认为200
    max-threads: 250
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹
    #（如：C:\Users\Shanhy\AppData\Local\Temp）
    basedir: C:/springboot-tomcat-tmp
    accesslog:
      # 打开Tomcat的Access日志，并可以设置日志格式的方法：
      enabled: true
      pattern:
      # accessLog目录，默认在basedir/logs
      directory: C:/springboot-tomcat-tmp/logs
##### 日志 #####
logging:
  # 日志文件目录
  path: C:/
  # 日志文件名称，默认为spring.log
  # file: spring.log
  ############################################################
  #
  # logback 配置
  #
  ############################################################
  config: classpath:logback.xml
  level:
    com.fans.dao: debug
##### Mybatis相关配置 #####
mybatis:
  type-aliases-package: com.fans.pojo
  mapper-locations: classpath:mappers/*.xml
##### 分页插件相关配置 #####
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
##### Spring相关配置 #####
spring:
  ############################################################
  #
  # devtools 热部署配置
  #
  ############################################################
  devtools:
    restart:
      # 热部署生效
      enabled: false
      # 设置重启的目录,添加那个目录的文件需要restart
      additional-paths: src/main/java
      # 排除那个目录的文件不需要restart
      exclude: static/**,public/**,WEB-INF/**
  mvc:
    # 设定静态文件路径，js,css等
    static-path-pattern: /static/**
  ############################################################
  #
  # thymeleaf 静态资源配置
  #
  ############################################################
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=utf-8
    # 关闭缓存, 即时刷新, 上线生产环境需要改为true
    cache: false
  ############################################################
  #
  # freemarker 静态资源配置
  #
  ############################################################
  freemarker:
    charset: UTF-8
    content-type: text/html;charset=utf-8
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
    cache: false
    template-loader-path: classpath:/templates
    settings:
      datetime_format: yyyy-MM-dd HH:mm:ss
      default_encoding: UTF-8
  ############################################################
  #
  # 资源文件配置
  #
  ############################################################
  messages:
    # 配置 资源文件，供thymeleaf 读取
    basename: properties/config
    # 缓存时间s
    cache-duration: 3600
    # 读取字符集
    encoding: UTF-8
  ############################################################
  #
  # 配置数据源相关	使用阿里巴巴的 druid 数据源
  #
  ############################################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf-8&serverTimezone=GMT&allowMultiQueries=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #--------------------------
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 1
    maxActive: 50
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    validationQueryTimeout: 3000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  ############################################################
  #
  # REDIS 配置
  #
  ############################################################
  redis:
    # redis数据库索引(默认为0)
    database: 0
    # redis服务器IP地址
    host: 127.0.0.1
    # redis端口号
    port: 6379
    # redis密码，默认为空
    password:
    # 连接redis超时时间（毫秒）
    timeout: 0
    #jedis连接池
    ###############################
    jedis:
      pool:
        # 最大等待时间
        max-wait: 1000
        # 最小空闲数量
        min-idle: 1
        # 最大空闲数量
        max-idle: 10
        # 最大连接数量
        max-active: 1000
  jackson:
    default-property-inclusion: non_null
swagger:
  show: true