spring:
  ############################################################
  #
  # thymeleaf 静态资源配置
  #
  ############################################################
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=utf-8
    # 关闭缓存, 即时刷新, 上线生产环境需要改为true
    cache: false
    check-template-location: false