##### 服务端相关配置 #####
server:
  # 配置api端口号
  port: 8080
  servlet:
    # 配置context-path, 一般来说这个配置在正式发布的时候不配置
    context-path: /
    # session最大超时时间(分钟)，默认为30分钟
    session:
      timeout: 60
  error:
    # 错误页，指定发生错误时，跳转的URL --> BasicErrorController
    path: /error
  # 该服务绑定IP地址，启动服务器时如本机不是该IP地址则抛出异常启动失败,
  # 只有特殊需求的情况下才配置, 具体根据各自的业务来设置
  address: 127.0.0.1
  tomcat:
    # tomcat最大线程数, 默认为200
    max-threads: 250
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹
    #（如：C:\Users\Shanhy\AppData\Local\Temp）
    basedir: ./tmp
    accesslog:
      # 打开Tomcat的Access日志，并可以设置日志格式的方法：
      enabled: true
      pattern:
      # accessLog目录，默认在basedir/logs
      directory: ./logs

