spring:
  ############################################################
  #
  # JPA 配置
  #
  ############################################################
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true