spring:
  ############################################################
  #
  # 资源文件配置
  #
  ############################################################
  messages:
    # 配置 资源文件，供thymeleaf 读取
    basename: properties/config
    # 缓存时间s
    cache-duration: 3600
    # 读取字符集
    encoding: UTF-8