spring:
  ############################################################
  #
  # REDIS 配置
  #
  ############################################################
  redis:
    # redis数据库索引(默认为0)
    database: 0
    # redis服务器IP地址
    host: 127.0.0.1
    # redis端口号
    port: 6379
    # redis密码，默认为空
    password: sl6819961
    # 连接redis超时时间（毫秒）
    timeout: 0
    #jedis连接池
    ###############################
    jedis:
      pool:
        # 最大等待时间
        max-wait: 1000
        # 最小空闲数量
        min-idle: 1
        # 最大空闲数量
        max-idle: 10
        # 最大连接数量
        max-active: 1000