##### 日志 #####
logging:
  # 日志文件目录
  #  path: C:/
  # 日志文件名称，默认为spring.log
  # file: spring.log
  ############################################################
  #
  # logback 配置
  #
  ############################################################
  config: classpath:logback.xml
  level:
    com.fans.dao: debug
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE